image: dolalti/ionic-build-android:latest #definir imagem

pipelines:
  custom:
    custom-api-deploy: #name of this pipeline
      - variables: #list variable names under here
          - name: APP_ID
          - name: CLIENT_URL
          - name: CLIENT_NAME
          - name: APP_SLUG
          - name: APP_SPLASH_COLOR
          - name: APP_FILE
          - name: S3_BUCKET
          - name: APP_OUT
      - step:
          size: 2x
          script:
            - npm install
            - gulp custom-build
            - aws s3 cp $APP_FILE $S3_BUCKET$APP_OUT --acl public-read
