image: atlassian/default-image:2

pipelines:
  custom:
    custom-api-deploy: #name of this pipeline
      - variables: #list variable names under here
          - name: APP_ID
          - name: CLIENT_URL
          - name: CLIENT_NAME
          - name: APP_SLUG
          - name: APP_SPLASH_COLOR
          - name: APP_FILE
          - name: S3_BUCKET
          - name: APP_OUT
      - step:
          # size: 2x
          script:
            - docker run -rm "$(pwd)":/app/ dolalti/flutter-build-android:latest -e APP_ID="${APP_ID}" -e CLIENT_URL="${CLIENT_URL}" -e CLIENT_NAME="${CLIENT_NAME}" -e APP_SLUG="${APP_SLUG}" -e APP_SPLASH_COLOR="${APP_SPLASH_COLOR}" -e APP_FILE="${APP_FILE}" -e S3_BUCKET="${S3_BUCKET}" -e APP_OUT="${APP_OUT}" ./build.sh
            - aws s3 cp $APP_FILE $S3_BUCKET$APP_OUT --acl public-read
          services:
            - docker
          caches:
            - docker
