image: dolalti/flutter-build-android:latest

pipelines:
  custom:
    custom-api-deploy: #name of this pipeline
      - variables: #list variable names under here
          - name: APP_ID
          - name: CLIENT_URL
          - name: CLIENT_NAME
          - name: APP_SLUG
          - name: APP_SPLASH_COLOR
          - name: APP_FILE
          - name: S3_BUCKET
          - name: APP_OUT
      - step:
          size: 2x
          script:
            - npm install
            - gulp prepare-build
            - flutter upgrade
            - flutter pub get
            - flutter pub run flutter_launcher_icons:main
            - flutter pub run flutter_native_splash:create
            - flutter build apk --release
            - cp build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app.apk
            - aws s3 cp $APP_FILE $S3_BUCKET$APP_OUT --acl public-read
          services:
            - docker
          caches:
            - docker
