services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weebet-front-v2
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    command: npm run dev

volumes:
  node_modules: