export const LSPORTS_FOOTBALL_ID = 6046;
export const LSPORTS_VOLLEYBALL_ID = 154830;
export const LSPORTS_BOXING_ID = 154919;
export const LSPORTS_TENNIS_ID = 54094;
export const LSPORTS_BASKETBALL_ID = 48242;

export const BETSAPI_FOOTBALL_ID = 1;
export const BETSAPI_BASKETBALL_ID = 18;
export const BETSAPI_VOLLEYBALL_ID = 91;
export const BETSAPI_BOXING_ID = 9;
export const BETSAPI_TENNIS_ID = 13;
export const BETSAPI_TABLE_TENNIS_ID = 92;
export const BETSAPI_AMERICAN_FOOTBALL_ID = 12;
export const BETSAPI_ICE_HOCKEY_ID = 17;
export const BETSAPI_FUTSAL_ID = 83;
export const BETSAPI_E_SPORTS_ID = 151;
