export default {
    'resultado_final': {
        chave: 'resultado_final',
        nome: 'Resultado Final',
        tempo: '90',
        colunas: 3,
        colunasMobile: 3,
        posicao: 1,
        odds: {
            'casa_90': { chave: 'casa_90', nome: 'Casa', sigla: 'Casa', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'empate_90': { chave: 'empate_90', nome: 'Empate', sigla: 'Empate', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'fora_90': { chave: 'fora_90', nome: 'Fora', sigla: 'Fora', posicaoX: 2, posicaoY: 0, posicaoXMobile: 2, posicaoYMobile: 0 }
        }
    },
    'dupla_chance': {
        chave: 'dupla_chance',
        nome: 'Dupla Chance',
        sportId: 1,
        tempo: '90',
        colunas: 3,
        colunasMobile: 1,
        odds: {
            'casa_empate_90': { chave: 'casa_empate_90', nome: 'Casa ou Empate', sigla: 'C+E', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'fora_empate_90': { chave: 'fora_empate_90', nome: 'Fora ou Empate', sigla: 'F+E', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'casa_fora_90': { chave: 'casa_fora_90', nome: 'Casa ou Fora', sigla: 'C+F', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
        }
    },
    'ambos_marcam': {
        chave: 'ambos_marcam',
        nome: 'Ambos os Times Marcam',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'ambos_marcam_sim_90': { chave: 'ambos_marcam_sim_90', nome: 'Sim', sigla: 'Amb', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'ambos_marcam_nao_90': { chave: 'ambos_marcam_nao_90', nome: 'Não', sigla: 'nAmb', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
        }
    },
    'condicionais': {
        chave: 'condicionais',
        nome: 'Condicionais',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 1,
        odds: {
            'casa_vence_fora_marca_90': { chave: 'casa_vence_fora_marca_90', nome: 'Casa Vence, Fora Marca', sigla: 'CvFm', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'casa_vence_fora_nao_marca_90': { chave: 'casa_vence_fora_nao_marca_90', nome: 'Casa Vence, Fora Não Marca', sigla: 'CvFnm', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'fora_vence_casa_marca_90': { chave: 'fora_vence_casa_marca_90', nome: 'Fora Vence, Casa Marca', sigla: 'FvCm', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 0 },
            'fora_vence_casa_nao_marca_90': { chave: 'fora_vence_casa_nao_marca_90', nome: 'Fora Vence, Casa Não Marca', sigla: 'FvCnm', posicaoX: 1, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 0 },
            'empate_com_gols_90': { chave: 'empate_com_gols_90', nome: 'Empate com Gols', sigla: 'Emp Cg', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 0 },
            'empate_sem_gols_90': { chave: 'empate_sem_gols_90', nome: 'Empate sem Gols', sigla: 'Emp Sg', posicaoX: 1, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 0 },
        }
    },
    'gols_partida': {
        chave: 'gols_partida',
        nome: 'Gols na Partida',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'gols_+1.5_90': { chave: 'gols_+1.5_90', nome: '+1.5', sigla: '+1.5G', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'gols_-1.5_90': { chave: 'gols_-1.5_90', nome: '-1.5', sigla: '-1.5G', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            'gols_+2.5_90': { chave: 'gols_+2.5_90', nome: '+2.5', sigla: '+2.5G', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            'gols_-2.5_90': { chave: 'gols_-2.5_90', nome: '-2.5', sigla: '-2.5G', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
            'gols_+3.5_90': { chave: 'gols_+3.5_90', nome: '+3.5', sigla: '+3.5G', posicaoX: 0, posicaoY: 3, posicaoXMobile: 0, posicaoYMobile: 3 },
            'gols_-3.5_90': { chave: 'gols_-3.5_90', nome: '-3.5', sigla: '-3.5G', posicaoX: 1, posicaoY: 3, posicaoXMobile: 1, posicaoYMobile: 3 },
            'gols_+4.5_90': { chave: 'gols_+4.5_90', nome: '+4.5', sigla: '+4.5G', posicaoX: 0, posicaoY: 4, posicaoXMobile: 0, posicaoYMobile: 4 },
            'gols_-4.5_90': { chave: 'gols_-4.5_90', nome: '-4.5', sigla: '-4.5G', posicaoX: 1, posicaoY: 4, posicaoXMobile: 1, posicaoYMobile: 4 },
            'gols_+5.5_90': { chave: 'gols_+5.5_90', nome: '+5.5', sigla: '+5.5G', posicaoX: 0, posicaoY: 5, posicaoXMobile: 0, posicaoYMobile: 5 },
            'gols_-5.5_90': { chave: 'gols_-5.5_90', nome: '-5.5', sigla: '-5.5G', posicaoX: 1, posicaoY: 5, posicaoXMobile: 1, posicaoYMobile: 5 },
            'gols_+6.5_90': { chave: 'gols_+6.5_90', nome: '+6.5', sigla: '+6.5G', posicaoX: 0, posicaoY: 6, posicaoXMobile: 0, posicaoYMobile: 6 },
            'gols_-6.5_90': { chave: 'gols_-6.5_90', nome: '-6.5', sigla: '-6.5G', posicaoX: 1, posicaoY: 6, posicaoXMobile: 1, posicaoYMobile: 6 },
        }
    },
    'handicap': {
        chave: 'handicap',
        nome: 'Handicap - Resultado',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'handicap_+1.5_casa': { chave: 'handicap_+1.5_casa', nome: 'Casa (-1)', sigla: 'C(-1)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'handicap_+1.5_fora': { chave: 'handicap_+1.5_fora', nome: 'Fora (-1)', sigla: 'F(-1)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'handicap_+2.5_casa': { chave: 'handicap_+2.5_casa', nome: 'Casa (-2)', sigla: 'C(-2)', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'handicap_+2.5_fora': { chave: 'handicap_+2.5_fora', nome: 'Fora (-2)', sigla: 'F(-2)', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            'handicap_+3.5_casa': { chave: 'handicap_+3.5_casa', nome: 'Casa (-3)', sigla: 'C(-3)', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            'handicap_+3.5_fora': { chave: 'handicap_+3.5_fora', nome: 'Fora (-3)', sigla: 'F(-3)', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
            'handicap_+4.5_casa': { chave: 'handicap_+4.5_casa', nome: 'Casa (-4)', sigla: 'C(-4)', posicaoX: 0, posicaoY: 3, posicaoXMobile: 0, posicaoYMobile: 3 },
            'handicap_+4.5_fora': { chave: 'handicap_+4.5_fora', nome: 'Fora (-4)', sigla: 'F(-4)', posicaoX: 1, posicaoY: 3, posicaoXMobile: 1, posicaoYMobile: 3 },

            'handicap_casa_+1': { chave: 'handicap_casa_+1', nome: 'Casa (+1)', sigla: 'C(+1)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'handicap_fora_+1': { chave: 'handicap_fora_+1', nome: 'Fora (+1)', sigla: 'F(+1)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'handicap_casa_+2': { chave: 'handicap_casa_+2', nome: 'Casa (+2)', sigla: 'C(+2)', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'handicap_fora_+2': { chave: 'handicap_fora_+2', nome: 'Fora (+2)', sigla: 'F(+2)', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            'handicap_casa_+3': { chave: 'handicap_casa_+3', nome: 'Casa (+3)', sigla: 'C(+3)', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            'handicap_fora_+3': { chave: 'handicap_fora_+3', nome: 'Fora (+3)', sigla: 'F(+3)', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
            'handicap_casa_+4': { chave: 'handicap_casa_+4', nome: 'Casa (+4)', sigla: 'C(+4)', posicaoX: 0, posicaoY: 3, posicaoXMobile: 0, posicaoYMobile: 3 },
            'handicap_fora_+4': { chave: 'handicap_fora_+4', nome: 'Fora (+4)', sigla: 'F(+4)', posicaoX: 1, posicaoY: 3, posicaoXMobile: 1, posicaoYMobile: 3 },
        }
    },
    'intervalo_fim_jogo': {
        chave: 'intervalo_fim_jogo',
        nome: 'Intervalo / Fim de Jogo',
        sportId: 1,
        tempo: '90',
        colunas: 3,
        colunasMobile: 1,
        odds: {
            'casa_1t_casa_f': { chave: 'casa_1t_casa_f', nome: 'Casa / Casa', sigla: 'C/C', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'casa_1t_empate_f': { chave: 'casa_1t_empate_f', nome: 'Casa / Empate', sigla: 'C/E', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'casa_1t_fora_f': { chave: 'casa_1t_fora_f', nome: 'Casa / Fora', sigla: 'C/F', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'empate_1t_casa_f': { chave: 'empate_1t_casa_f', nome: 'Empate / Casa', sigla: 'E/C', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 0 },
            'empate_1t_empate_f': { chave: 'empate_1t_empate_f', nome: 'Empate / Empate', sigla: 'E/E', posicaoX: 1, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 0 },
            'empate_1t_fora_f': { chave: 'empate_1t_fora_f', nome: 'Empate / Fora', sigla: 'E/F', posicaoX: 2, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 0 },
            'fora_1t_casa_f': { chave: 'fora_1t_casa_f', nome: 'Fora / Casa', sigla: 'F/C', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 0 },
            'fora_1t_empate_f': { chave: 'fora_1t_empate_f', nome: 'Fora / Empate', sigla: 'F/E', posicaoX: 1, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 0 },
            'fora_1t_fora_f': { chave: 'fora_1t_fora_f', nome: 'Fora / Fora', sigla: 'F/F', posicaoX: 2, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 0 },
        }
    },
    'empate_anula_aposta': {
        chave: 'empate_anula_aposta',
        nome: 'Empate Anula Aposta',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'empate_anula_aposta_casa': { chave: 'empate_anula_aposta_casa', nome: 'Casa', sigla: 'Casa', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'empate_anula_aposta_fora': { chave: 'empate_anula_aposta_fora', nome: 'Fora', sigla: 'Fora', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
        }
    },
    'total_exato_gols': {
        chave: 'total_exato_gols',
        nome: 'Total Exato de Gols',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'total_gols_0_90': { chave: 'total_gols_0_90', nome: '0 Gols', sigla: '0G', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'total_gols_1_90': { chave: 'total_gols_1_90', nome: '1 Gol', sigla: '1G', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'total_gols_2_90': { chave: 'total_gols_2_90', nome: '2 Gols', sigla: '2G', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            'total_gols_3_90': { chave: 'total_gols_3_90', nome: '3 Gols', sigla: '3G', posicaoX: 0, posicaoY: 3, posicaoXMobile: 0, posicaoYMobile: 3 },
            'total_gols_4_90': { chave: 'total_gols_4_90', nome: '4 Gols', sigla: '4G', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'total_gols_5_90': { chave: 'total_gols_5_90', nome: '5 Gols', sigla: '5G', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            'total_gols_6_90': { chave: 'total_gols_6_90', nome: '6 Gols', sigla: '6G', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
            'total_gols_+7_90': { chave: 'total_gols_+7_90', nome: '+7 Gols', sigla: '+7G', posicaoX: 1, posicaoY: 3, posicaoXMobile: 1, posicaoYMobile: 3 },
        }
    },
    'ultimo_marcar_gol': {
        chave: 'ultimo_marcar_gol',
        nome: 'Última Equipe a Marcar',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'casa_marca_ultimo': { chave: 'casa_marca_ultimo', nome: 'Casa', sigla: 'CM Último', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'fora_marca_ultimo': { chave: 'fora_marca_ultimo', nome: 'Fora', sigla: 'FM Último', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 }
        }
    },
    'total_gols_casa': {
        chave: 'total_gols_casa',
        nome: 'Casa - Total de Gols',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'casa_marca_+1.5_90': { chave: 'casa_marca_+1.5_90', nome: 'Mais de 1.5', sigla: '+1.5G C', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'casa_marca_+2.5_90': { chave: 'casa_marca_+2.5_90', nome: 'Mais de 2.5', sigla: '+2.5G C', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'casa_marca_+3.5_90': { chave: 'casa_marca_+3.5_90', nome: 'Mais de 3.5', sigla: '+3.5G C', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            'casa_marca_+4.5_90': { chave: 'casa_marca_+4.5_90', nome: 'Mais de 4.5', sigla: '+4.5G C', posicaoX: 0, posicaoY: 3, posicaoXMobile: 0, posicaoYMobile: 3 },
            'casa_marca_-1.5_90': { chave: 'casa_marca_-1.5_90', nome: 'Menos de 1.5', sigla: '-1.5G C', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'casa_marca_-2.5_90': { chave: 'casa_marca_-2.5_90', nome: 'Menos de 2.5', sigla: '-2.5G C', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            'casa_marca_-3.5_90': { chave: 'casa_marca_-3.5_90', nome: 'Menos de 3.5', sigla: '-3.5G C', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
            'casa_marca_-4.5_90': { chave: 'casa_marca_-4.5_90', nome: 'Menos de 4.5', sigla: '-4.5G C', posicaoX: 1, posicaoY: 3, posicaoXMobile: 1, posicaoYMobile: 3 },
        }
    },
    'total_gols_fora': {
        chave: 'total_gols_fora',
        nome: 'Fora - Total de Gols',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'fora_marca_+1.5_90': { chave: 'fora_marca_+1.5_90', nome: 'Mais de 1.5', sigla: '+1.5G F', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'fora_marca_+2.5_90': { chave: 'fora_marca_+2.5_90', nome: 'Mais de 2.5', sigla: '+2.5G F', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'fora_marca_+3.5_90': { chave: 'fora_marca_+3.5_90', nome: 'Mais de 3.5', sigla: '+3.5G F', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            'fora_marca_+4.5_90': { chave: 'fora_marca_+4.5_90', nome: 'Mais de 4.5', sigla: '+4.5G F', posicaoX: 0, posicaoY: 3, posicaoXMobile: 0, posicaoYMobile: 3 },
            'fora_marca_-1.5_90': { chave: 'fora_marca_-1.5_90', nome: 'Menos de 1.5', sigla: '-1.5G F', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'fora_marca_-2.5_90': { chave: 'fora_marca_-2.5_90', nome: 'Menos de 2.5', sigla: '-2.5G F', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            'fora_marca_-3.5_90': { chave: 'fora_marca_-3.5_90', nome: 'Menos de 3.5', sigla: '-3.5G F', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
            'fora_marca_-4.5_90': { chave: 'fora_marca_-4.5_90', nome: 'Menos de 4.5', sigla: '-4.5G F', posicaoX: 1, posicaoY: 3, posicaoXMobile: 1, posicaoYMobile: 3 },
        }
    },
    'casa_gols_exato': {
        chave: 'casa_gols_exato',
        nome: 'Time da Casa - Gols Exatos',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'gols_exatos_0_casa_90': { chave: 'gols_exatos_0_casa_90', nome: '0 Gols', sigla: 'C 0G', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'gols_exatos_1_casa_90': { chave: 'gols_exatos_1_casa_90', nome: '1 Gol', sigla: 'C 1G', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'gols_exatos_2_casa_90': { chave: 'gols_exatos_2_casa_90', nome: '2 Gols', sigla: 'C 2G', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'gols_exatos_3+_casa_90': { chave: 'gols_exatos_3+_casa_90', nome: '3+ Gols', sigla: 'C 3+G', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
        }
    },
    'fora_gols_exato': {
        chave: 'fora_gols_exato',
        nome: 'Time da Fora - Gols Exatos',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'gols_exatos_0_fora_90': { chave: 'gols_exatos_0_fora_90', nome: '0 Gols', sigla: 'F 0G', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'gols_exatos_1_fora_90': { chave: 'gols_exatos_1_fora_90', nome: '1 Gol', sigla: 'F 1G', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'gols_exatos_2_fora_90': { chave: 'gols_exatos_2_fora_90', nome: '2 Gols', sigla: 'F 2G', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'gols_exatos_3+_fora_90': { chave: 'gols_exatos_3+_fora_90', nome: '3+ Gols', sigla: 'F 3+G', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 0 },
        }
    },
    'par_impar': {
        chave: 'par_impar',
        nome: 'Gols Ímpar/Par',
        sportId: 1,
        tempo: '90',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'total_gols_impar_90': { chave: 'total_gols_impar_90', nome: 'Impar', sigla: 'Ímpar', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'total_gols_par_90': { chave: 'total_gols_par_90', nome: 'Par', sigla: 'Par', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'casa_impar_90': { chave: 'casa_impar_90', nome: 'Casa Impar', sigla: 'C Imp', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'casa_par_90': { chave: 'casa_par_90', nome: 'Casa Par', sigla: 'C Par', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            'fora_impar_90': { chave: 'fora_impar_90', nome: 'Fora Impar', sigla: 'F Imp', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            'fora_par_90': { chave: 'fora_par_90', nome: 'Fora Par', sigla: 'F Par', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
        }
    },
    'escanteios': {
        chave: 'escanteios',
        nome: 'Escanteios',
        sportId: 1,
        tempo: '90',
        colunas: 3,
        colunasMobile: 1,
        odds: {
            'escanteios_mais_de_6': { chave: 'escanteios_mais_de_6', nome: 'Mais de 6', sigla: '+6 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_6': { chave: 'escanteios_exatamente_6', nome: 'Exatamente 6', sigla: '6 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_6': { chave: 'escanteios_menos_de_6', nome: 'Menos de 6', sigla: '-6 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_7': { chave: 'escanteios_mais_de_7', nome: 'Mais de 7', sigla: '+7 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_7': { chave: 'escanteios_exatamente_7', nome: 'Exatamente 7', sigla: '7 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_7': { chave: 'escanteios_menos_de_7', nome: 'Menos de 7', sigla: '-7 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_8': { chave: 'escanteios_mais_de_8', nome: 'Mais de 8', sigla: '+8 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_8': { chave: 'escanteios_exatamente_8', nome: 'Exatamente 8', sigla: '8 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_8': { chave: 'escanteios_menos_de_8', nome: 'Menos de 8', sigla: '-8 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_9': { chave: 'escanteios_mais_de_9', nome: 'Mais de 9', sigla: '+9 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_9': { chave: 'escanteios_exatamente_9', nome: 'Exatamente 9', sigla: '9 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_9': { chave: 'escanteios_menos_de_9', nome: 'Menos de 9', sigla: '-9 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_10': { chave: 'escanteios_mais_de_10', nome: 'Mais de 10', sigla: '+10 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_10': { chave: 'escanteios_exatamente_10', nome: 'Exatamente 10', sigla: '10 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_10': { chave: 'escanteios_menos_de_10', nome: 'Menos de 10', sigla: '-10 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_11': { chave: 'escanteios_mais_de_11', nome: 'Mais de 11', sigla: '+1 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_11': { chave: 'escanteios_exatamente_11', nome: 'Exatamente 11', sigla: '11 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_11': { chave: 'escanteios_menos_de_11', nome: 'Menos de 11', sigla: '-11 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_12': { chave: 'escanteios_mais_de_12', nome: 'Mais de 12', sigla: '+12 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_12': { chave: 'escanteios_exatamente_12', nome: 'Exatamente 12', sigla: '12 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_12': { chave: 'escanteios_menos_de_12', nome: 'Menos de 12', sigla: '-12 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_13': { chave: 'escanteios_mais_de_13', nome: 'Mais de 13', sigla: '+13 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_13': { chave: 'escanteios_exatamente_13', nome: 'Exatamente 13', sigla: '13 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_13': { chave: 'escanteios_menos_de_13', nome: 'Menos de 13', sigla: '-13 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_14': { chave: 'escanteios_mais_de_14', nome: 'Mais de 14', sigla: '+14 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_14': { chave: 'escanteios_exatamente_14', nome: 'Exatamente 14', sigla: '14 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_14': { chave: 'escanteios_menos_de_14', nome: 'Menos de 14', sigla: '-14 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_15': { chave: 'escanteios_mais_de_15', nome: 'Mais de 15', sigla: '+15 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_15': { chave: 'escanteios_exatamente_15', nome: 'Exatamente 15', sigla: '15 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_15': { chave: 'escanteios_menos_de_15', nome: 'Menos de 15', sigla: '-15 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_mais_de_16': { chave: 'escanteios_mais_de_16', nome: 'Mais de 16', sigla: '+16 ESCT', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_exatamente_16': { chave: 'escanteios_exatamente_16', nome: 'Exatamente 16', sigla: '16 ESCT', posicaoX: 1, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'escanteios_menos_de_16': { chave: 'escanteios_menos_de_16', nome: 'Menos de 16', sigla: '-16 ESCT', posicaoX: 2, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
        }
    },
    'placar_exato': {
        chave: 'placar_exato',
        nome: 'Placar Exato',
        sportId: 1,
        tempo: '90',
        colunas: 3,
        colunasMobile: 3,
        odds: {
            '1x0_90': { chave: '1x0_90', nome: '1x0', sigla: '1x0', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            '2x0_90': { chave: '2x0_90', nome: '2x0', sigla: '2x0', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            '2x1_90': { chave: '2x1_90', nome: '2x1', sigla: '2x1', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            '3x0_90': { chave: '3x0_90', nome: '3x0', sigla: '3x0', posicaoX: 0, posicaoY: 3, posicaoXMobile: 0, posicaoYMobile: 3 },
            '3x1_90': { chave: '3x1_90', nome: '3x1', sigla: '3x1', posicaoX: 0, posicaoY: 4, posicaoXMobile: 0, posicaoYMobile: 4 },
            '3x2_90': { chave: '3x2_90', nome: '3x2', sigla: '3x2', posicaoX: 0, posicaoY: 5, posicaoXMobile: 0, posicaoYMobile: 5 },
            '4x0_90': { chave: '4x0_90', nome: '4x0', sigla: '4x0', posicaoX: 0, posicaoY: 6, posicaoXMobile: 0, posicaoYMobile: 6 },
            '4x1_90': { chave: '4x1_90', nome: '4x1', sigla: '4x1', posicaoX: 0, posicaoY: 7, posicaoXMobile: 0, posicaoYMobile: 7 },
            '4x2_90': { chave: '4x2_90', nome: '4x2', sigla: '4x2', posicaoX: 0, posicaoY: 8, posicaoXMobile: 0, posicaoYMobile: 8 },
            '4x3_90': { chave: '4x3_90', nome: '4x3', sigla: '4x3', posicaoX: 0, posicaoY: 9, posicaoXMobile: 0, posicaoYMobile: 9 },
            '5x0_90': { chave: '5x0_90', nome: '5x0', sigla: '5x0', posicaoX: 0, posicaoY: 10, posicaoXMobile: 0, posicaoYMobile: 10 },
            '5x1_90': { chave: '5x1_90', nome: '5x1', sigla: '5x1', posicaoX: 0, posicaoY: 11, posicaoXMobile: 0, posicaoYMobile: 11 },
            '5x2_90': { chave: '5x2_90', nome: '5x2', sigla: '5x2', posicaoX: 0, posicaoY: 12, posicaoXMobile: 0, posicaoYMobile: 12 },
            '5x3_90': { chave: '5x3_90', nome: '5x3', sigla: '5x3', posicaoX: 0, posicaoY: 13, posicaoXMobile: 0, posicaoYMobile: 13 },
            '5x4_90': { chave: '5x4_90', nome: '5x4', sigla: '5x4', posicaoX: 0, posicaoY: 14, posicaoXMobile: 0, posicaoYMobile: 14 },
            '6x0_90': { chave: '6x0_90', nome: '6x0', sigla: '6x0', posicaoX: 0, posicaoY: 15, posicaoXMobile: 0, posicaoYMobile: 15 },
            '6x1_90': { chave: '6x1_90', nome: '6x1', sigla: '6x1', posicaoX: 0, posicaoY: 16, posicaoXMobile: 0, posicaoYMobile: 16 },
            '6x2_90': { chave: '6x2_90', nome: '6x2', sigla: '6x2', posicaoX: 0, posicaoY: 17, posicaoXMobile: 0, posicaoYMobile: 17 },
            '6x3_90': { chave: '6x3_90', nome: '6x3', sigla: '6x3', posicaoX: 0, posicaoY: 18, posicaoXMobile: 0, posicaoYMobile: 18 },
            '6x4_90': { chave: '6x4_90', nome: '6x4', sigla: '6x4', posicaoX: 0, posicaoY: 19, posicaoXMobile: 0, posicaoYMobile: 19 },
            '6x5_90': { chave: '6x5_90', nome: '6x5', sigla: '6x5', posicaoX: 0, posicaoY: 20, posicaoXMobile: 0, posicaoYMobile: 20 },


            '0x0_90': { chave: '0x0_90', nome: '0x0', sigla: '0x0', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            '1x1_90': { chave: '1x1_90', nome: '1x1', sigla: '1x1', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            '2x2_90': { chave: '2x2_90', nome: '2x2', sigla: '2x2', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
            '3x3_90': { chave: '3x3_90', nome: '3x3', sigla: '3x3', posicaoX: 1, posicaoY: 3, posicaoXMobile: 1, posicaoYMobile: 3 },
            '4x4_90': { chave: '4x4_90', nome: '4x4', sigla: '4x4', posicaoX: 1, posicaoY: 4, posicaoXMobile: 1, posicaoYMobile: 4 },
            '5x5_90': { chave: '5x5_90', nome: '5x5', sigla: '5x5', posicaoX: 1, posicaoY: 5, posicaoXMobile: 1, posicaoYMobile: 5 },
            '6x6_90': { chave: '6x6_90', nome: '6x6', sigla: '6x6', posicaoX: 1, posicaoY: 6, posicaoXMobile: 1, posicaoYMobile: 6 },

            '0x1_90': { chave: '0x1_90', nome: '0x1', sigla: '0x1', posicaoX: 2, posicaoY: 0, posicaoXMobile: 2, posicaoYMobile: 0 },
            '0x2_90': { chave: '0x2_90', nome: '0x2', sigla: '0x2', posicaoX: 2, posicaoY: 1, posicaoXMobile: 2, posicaoYMobile: 1 },
            '1x2_90': { chave: '1x2_90', nome: '1x2', sigla: '1x2', posicaoX: 2, posicaoY: 2, posicaoXMobile: 2, posicaoYMobile: 2 },
            '0x3_90': { chave: '0x3_90', nome: '0x3', sigla: '0x3', posicaoX: 2, posicaoY: 3, posicaoXMobile: 2, posicaoYMobile: 3 },
            '1x3_90': { chave: '1x3_90', nome: '1x3', sigla: '1x3', posicaoX: 2, posicaoY: 4, posicaoXMobile: 2, posicaoYMobile: 4 },
            '2x3_90': { chave: '2x3_90', nome: '2x3', sigla: '2x3', posicaoX: 2, posicaoY: 5, posicaoXMobile: 2, posicaoYMobile: 5 },
            '0x4_90': { chave: '0x4_90', nome: '0x4', sigla: '0x4', posicaoX: 2, posicaoY: 6, posicaoXMobile: 2, posicaoYMobile: 6 },
            '1x4_90': { chave: '1x4_90', nome: '1x4', sigla: '1x4', posicaoX: 2, posicaoY: 7, posicaoXMobile: 2, posicaoYMobile: 7 },
            '2x4_90': { chave: '2x4_90', nome: '2x4', sigla: '2x4', posicaoX: 2, posicaoY: 8, posicaoXMobile: 2, posicaoYMobile: 8 },
            '3x4_90': { chave: '3x4_90', nome: '3x4', sigla: '3x4', posicaoX: 2, posicaoY: 9, posicaoXMobile: 2, posicaoYMobile: 9 },
            '0x5_90': { chave: '0x5_90', nome: '0x5', sigla: '0x5', posicaoX: 2, posicaoY: 10, posicaoXMobile: 2, posicaoYMobile: 10 },
            '1x5_90': { chave: '1x5_90', nome: '1x5', sigla: '1x5', posicaoX: 2, posicaoY: 11, posicaoXMobile: 2, posicaoYMobile: 11 },
            '2x5_90': { chave: '2x5_90', nome: '2x5', sigla: '2x5', posicaoX: 2, posicaoY: 12, posicaoXMobile: 2, posicaoYMobile: 12 },
            '3x5_90': { chave: '3x5_90', nome: '3x5', sigla: '3x5', posicaoX: 2, posicaoY: 13, posicaoXMobile: 2, posicaoYMobile: 13 },
            '4x5_90': { chave: '4x5_90', nome: '4x5', sigla: '4x5', posicaoX: 2, posicaoY: 14, posicaoXMobile: 2, posicaoYMobile: 14 },
            '0x6_90': { chave: '0x6_90', nome: '0x6', sigla: '0x6', posicaoX: 2, posicaoY: 15, posicaoXMobile: 2, posicaoYMobile: 15 },
            '1x6_90': { chave: '1x6_90', nome: '1x6', sigla: '1x6', posicaoX: 2, posicaoY: 16, posicaoXMobile: 2, posicaoYMobile: 16 },
            '2x6_90': { chave: '2x6_90', nome: '2x6', sigla: '2x6', posicaoX: 2, posicaoY: 17, posicaoXMobile: 2, posicaoYMobile: 17 },
            '3x6_90': { chave: '3x6_90', nome: '3x6', sigla: '3x6', posicaoX: 2, posicaoY: 18, posicaoXMobile: 2, posicaoYMobile: 18 },
            '4x6_90': { chave: '4x6_90', nome: '4x6', sigla: '4x6', posicaoX: 2, posicaoY: 19, posicaoXMobile: 2, posicaoYMobile: 19 },
            '5x6_90': { chave: '5x6_90', nome: '5x6', sigla: '5x6', posicaoX: 2, posicaoY: 20, posicaoXMobile: 2, posicaoYMobile: 20 },
        }
    },
    'resultado_1t': {
        chave: 'resultado_1t',
        nome: '1º Tempo - Resultado',
        sportId: 1,
        tempo: '1T',
        colunas: 3,
        colunasMobile: 3,
        odds: {
            'casa_1t': { chave: 'casa_1t', nome: 'Casa', sigla: 'Casa(1T)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'empate_1t': { chave: 'empate_1t', nome: 'Empate', sigla: 'Emp(1T)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'fora_1t': { chave: 'fora_1t', nome: 'Fora', sigla: 'Fora(1T)', posicaoX: 2, posicaoY: 0, posicaoXMobile: 2, posicaoYMobile: 0 },
        }
    },
    'ambos_marcam_1t': {
        chave: 'ambos_marcam_1t',
        nome: '1º Tempo - Ambos os Times Marcam',
        sportId: 1,
        tempo: '1T',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'ambos_marcam_sim_1t': { chave: 'ambos_marcam_sim_1t', nome: 'Sim', sigla: 'Amb(1T)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'ambos_marcam_nao_1t': { chave: 'ambos_marcam_nao_1t', nome: 'Não', sigla: 'nAmb(1T)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
        }
    },
    'handicap_1t': {
        chave: 'handicap_1t',
        nome: '1º Tempo - Handicap - Resultado',
        sportId: 1,
        tempo: '1T',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'handicap_casa_-1_1t': { chave: 'handicap_casa_-1_1t', nome: 'Casa (-1)', sigla: 'C(-1)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'handicap_fora_-1_1t': { chave: 'handicap_fora_-1_1t', nome: 'Fora (-1)', sigla: 'F(-1)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'handicap_casa_-2_1t': { chave: 'handicap_casa_-2_1t', nome: 'Casa (-2)', sigla: 'C(-2)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'handicap_fora_-2_1t': { chave: 'handicap_fora_-2_1t', nome: 'Fora (-2)', sigla: 'F(-2)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'handicap_casa_-3_1t': { chave: 'handicap_casa_-3_1t', nome: 'Casa (-3)', sigla: 'C(-3)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'handicap_fora_-3_1t': { chave: 'handicap_fora_-3_1t', nome: 'Fora (-3)', sigla: 'F(-3)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'handicap_casa_-4_1t': { chave: 'handicap_casa_-4_1t', nome: 'Casa (-4)', sigla: 'C(-4)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'handicap_fora_-4_1t': { chave: 'handicap_fora_-4_1t', nome: 'Fora (-4)', sigla: 'F(-4)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },

            'handicap_casa_+1_1t': { chave: 'handicap_casa_+1_1t', nome: 'Casa (+1)', sigla: 'C(+1)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'handicap_fora_+1_1t': { chave: 'handicap_fora_+1_1t', nome: 'Fora (+1)', sigla: 'F(+1)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'handicap_casa_+2_1t': { chave: 'handicap_casa_+2_1t', nome: 'Casa (+2)', sigla: 'C(+2)', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'handicap_fora_+2_1t': { chave: 'handicap_fora_+2_1t', nome: 'Fora (+2)', sigla: 'F(+2)', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            'handicap_casa_+3_1t': { chave: 'handicap_casa_+3_1t', nome: 'Casa (+3)', sigla: 'C(+3)', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            'handicap_fora_+3_1t': { chave: 'handicap_fora_+3_1t', nome: 'Fora (+3)', sigla: 'F(+3)', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
            'handicap_casa_+4_1t': { chave: 'handicap_casa_+4_1t', nome: 'Casa (+4)', sigla: 'C(+4)', posicaoX: 0, posicaoY: 3, posicaoXMobile: 0, posicaoYMobile: 3 },
            'handicap_fora_+4_1t': { chave: 'handicap_fora_+4_1t', nome: 'Fora (+4)', sigla: 'F(+4)', posicaoX: 1, posicaoY: 3, posicaoXMobile: 1, posicaoYMobile: 3 },
        }
    },
    'gols_partida_1t': {
        chave: 'gols_partida_1t',
        nome: '1º Tempo - Gols na Partida',
        sportId: 1,
        tempo: '1T',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'gols_+0.5_1t': { chave: 'gols_+0.5_1t', nome: '+0.5', sigla: '+0.5G(1T)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'gols_-0.5_1t': { chave: 'gols_-0.5_1t', nome: '-0.5', sigla: '-0.5G(1T)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'gols_+1.5_1t': { chave: 'gols_+1.5_1t', nome: '+1.5', sigla: '+1.5G(1T)', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            'gols_-1.5_1t': { chave: 'gols_-1.5_1t', nome: '-1.5', sigla: '-1.5G(1T)', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            'gols_+2.5_1t': { chave: 'gols_+2.5_1t', nome: '+2.5', sigla: '+2.5G(1T)', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            'gols_-2.5_1t': { chave: 'gols_-2.5_1t', nome: '-2.5', sigla: '-2.5G(1T)', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
        }
    },
    'par_impar_1t': {
        chave: 'par_impar_1t',
        nome: '1º Tempo - Gols Ímpar/Par',
        sportId: 1,
        tempo: '1T',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'total_gols_impar_1t': { chave: 'total_gols_impar_1t', nome: 'Impar', sigla: 'Ímpar(1T)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'total_gols_par_1t': { chave: 'total_gols_par_1t', nome: 'Par', sigla: 'Par(1T)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
        }
    },
    'placar_exato_1t': {
        chave: 'placar_exato_1t',
        nome: '1º Tempo - Placar Exato',
        sportId: 1,
        tempo: '1T',
        colunas: 3,
        colunasMobile: 3,
        odds: {
            '1x0_1t': { chave: '1x0_1t', nome: '1x0', sigla: '1x0(1T)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            '2x0_1t': { chave: '2x0_1t', nome: '2x0', sigla: '2x0(1T)', posicaoX: 0, posicaoY: 1, posicaoXMobile: 0, posicaoYMobile: 1 },
            '2x1_1t': { chave: '2x1_1t', nome: '2x1', sigla: '2x1(1T)', posicaoX: 0, posicaoY: 2, posicaoXMobile: 0, posicaoYMobile: 2 },
            '3x0_1t': { chave: '3x0_1t', nome: '3x0', sigla: '3x0(1T)', posicaoX: 0, posicaoY: 3, posicaoXMobile: 0, posicaoYMobile: 3 },
            '3x1_1t': { chave: '3x1_1t', nome: '3x1', sigla: '3x1(1T)', posicaoX: 0, posicaoY: 4, posicaoXMobile: 0, posicaoYMobile: 4 },
            '3x2_1t': { chave: '3x2_1t', nome: '3x2', sigla: '3x2(1T)', posicaoX: 0, posicaoY: 5, posicaoXMobile: 0, posicaoYMobile: 5 },
            '4x0_1t': { chave: '4x0_1t', nome: '4x0', sigla: '4x0(1T)', posicaoX: 0, posicaoY: 6, posicaoXMobile: 0, posicaoYMobile: 6 },
            '4x1_1t': { chave: '4x1_1t', nome: '4x1', sigla: '4x1(1T)', posicaoX: 0, posicaoY: 7, posicaoXMobile: 0, posicaoYMobile: 7 },
            '4x2_1t': { chave: '4x2_1t', nome: '4x2', sigla: '4x2(1T)', posicaoX: 0, posicaoY: 8, posicaoXMobile: 0, posicaoYMobile: 8 },
            '4x3_1t': { chave: '4x3_1t', nome: '4x3', sigla: '4x3(1T)', posicaoX: 0, posicaoY: 9, posicaoXMobile: 0, posicaoYMobile: 9 },


            '0x0_1t': { chave: '0x0_1t', nome: '0x0', sigla: '0x0(1T)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            '1x1_1t': { chave: '1x1_1t', nome: '1x1', sigla: '1x1(1T)', posicaoX: 1, posicaoY: 1, posicaoXMobile: 1, posicaoYMobile: 1 },
            '2x2_1t': { chave: '2x2_1t', nome: '2x2', sigla: '2x2(1T)', posicaoX: 1, posicaoY: 2, posicaoXMobile: 1, posicaoYMobile: 2 },
            '3x3_1t': { chave: '3x3_1t', nome: '3x3', sigla: '3x3(1T)', posicaoX: 1, posicaoY: 3, posicaoXMobile: 1, posicaoYMobile: 3 },
            '4x4_1t': { chave: '4x4_1t', nome: '4x4', sigla: '4x4(1T)', posicaoX: 1, posicaoY: 4, posicaoXMobile: 1, posicaoYMobile: 4 },

            '0x1_1t': { chave: '0x1_1t', nome: '0x1', sigla: '0x1(1T)', posicaoX: 2, posicaoY: 0, posicaoXMobile: 2, posicaoYMobile: 0 },
            '0x2_1t': { chave: '0x2_1t', nome: '0x2', sigla: '0x2(1T)', posicaoX: 2, posicaoY: 1, posicaoXMobile: 2, posicaoYMobile: 1 },
            '1x2_1t': { chave: '1x2_1t', nome: '1x2', sigla: '1x2(1T)', posicaoX: 2, posicaoY: 2, posicaoXMobile: 2, posicaoYMobile: 2 },
            '0x3_1t': { chave: '0x3_1t', nome: '0x3', sigla: '0x3(1T)', posicaoX: 2, posicaoY: 3, posicaoXMobile: 2, posicaoYMobile: 3 },
            '1x3_1t': { chave: '1x3_1t', nome: '1x3', sigla: '1x3(1T)', posicaoX: 2, posicaoY: 4, posicaoXMobile: 2, posicaoYMobile: 4 },
            '2x3_1t': { chave: '2x3_1t', nome: '2x3', sigla: '2x3(1T)', posicaoX: 2, posicaoY: 5, posicaoXMobile: 2, posicaoYMobile: 5 },
            '0x4_1t': { chave: '0x4_1t', nome: '0x4', sigla: '0x4(1T)', posicaoX: 2, posicaoY: 6, posicaoXMobile: 2, posicaoYMobile: 6 },
            '1x4_1t': { chave: '1x4_1t', nome: '1x4', sigla: '1x4(1T)', posicaoX: 2, posicaoY: 7, posicaoXMobile: 2, posicaoYMobile: 7 },
            '2x4_1t': { chave: '2x4_1t', nome: '2x4', sigla: '2x4(1T)', posicaoX: 2, posicaoY: 8, posicaoXMobile: 2, posicaoYMobile: 8 },
            '3x4_1t': { chave: '3x4_1t', nome: '3x4', sigla: '3x4(1T)', posicaoX: 2, posicaoY: 9, posicaoXMobile: 2, posicaoYMobile: 9 },
        }
    },
    'resultado_2t': {
        chave: 'resultado_2t',
        nome: '2º Tempo - Resultado',
        sportId: 1,
        tempo: '2T',
        colunas: 3,
        colunasMobile: 3,
        odds: {
            'casa_2t': { chave: 'casa_2t', nome: 'Casa', sigla: 'Casa(2T)', categoriaChave: 'resultado_2t', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'empate_2t': { chave: 'empate_2t', nome: 'Empate', sigla: 'Empate(2T)', categoriaChave: 'resultado_2t', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
            'fora_2t': { chave: 'fora_2t', nome: 'Fora', sigla: 'Fora(2T)', categoriaChave: 'resultado_2t', posicaoX: 2, posicaoY: 0, posicaoXMobile: 2, posicaoYMobile: 0 },
        }
    },
    'ambos_marcam_2t': {
        chave: 'ambos_marcam_2t',
        nome: '2º Tempo - Ambos os Times Marcam',
        sportId: 1,
        tempo: '2T',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'ambos_marcam_sim_2t': { chave: 'ambos_marcam_sim_2t', nome: 'Sim', sigla: 'Amb(2T)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'ambos_marcam_nao_2t': { chave: 'ambos_marcam_nao_2t', nome: 'Não', sigla: 'nAmb(2T)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
        }
    },
    'par_impar_2t': {
        chave: 'par_impar_2t',
        nome: '2º Tempo - Gols Ímpar/Par',
        sportId: 1,
        tempo: '2T',
        colunas: 2,
        colunasMobile: 2,
        odds: {
            'total_gols_impar_2t': { chave: 'total_gols_impar_2t', nome: 'Impar', sigla: 'Ímpar(2T)', posicaoX: 0, posicaoY: 0, posicaoXMobile: 0, posicaoYMobile: 0 },
            'total_gols_par_2t': { chave: 'total_gols_par_2t', nome: 'Par', sigla: 'Par(2T)', posicaoX: 1, posicaoY: 0, posicaoXMobile: 1, posicaoYMobile: 0 },
        }
    },
};
