export const countriesWithMasculineNames = [
    'AFEGANISTÃO',
    'ALBÂNIA',
    'ANTÍGUA E BARBUDA',
    'AZERBAIJÃO',
    'BAHREIN',
    'BANGLADESH',
    'BARBADOS',
    'BELIZE',
    'BENIM',
    'BUTÃO',
    'BOLÍVIA',
    'BOTSUANA',
    'BRUNEI',
    'BRASIL',
    'BULGÁRIA',
    'BURKINA FASO',
    'BURUNDI',
    'CABO VERDE',
    'CAMARÕES',
    'CANADÁ',
    'CATAR',
    'CAZAQUISTÃO',
    'CHADE',
    'CHILE',
    'CHIPRE',
    'COLÔMBIA',
    'COMORES',
    'CONGO',
    'COSTA DO MARFIM',
    'CUBA',
    'DJIBOUTI',
    'DOMINICA',
    'EGITO',
    'EL SALVADOR',
    'EMIRADOS ÁRABES UNIDOS',
    'EQUADOR',
    'ERITREIA',
    'ESWATINI',
    'ESTADOS UNIDOS',
    'ETIÓPIA',
    'FILIPINAS',
    'FIJI',
    'GABÃO',
    'GÂMBIA',
    'GANA',
    'GRANADA',
    'GRÉCIA',
    'GUATEMALA',
    'GUINÉ',
    'GUINÉ-BISSAU',
    'GUINÉ EQUATORIAL',
    'HAITI',
    'HOLANDA',
    'HONDURAS',
    'HUNGRIA',
    'IÊMEN',
    'ILHAS MARSHALL',
    'ILHAS SALOMÃO',
    'ILHAS SEYCHELLES',
    'ILHAS COMORES',
    'ÍNDIA',
    'INDONÉSIA',
    'IRÃ',
    'IRAQUE',
    'ISRAEL',
    'ITÁLIA',
    'JAPÃO',
    'JORDÂNIA',
    'KOSOVO',
    'KUWAIT',
    'LAOS',
    'LÍBANO',
    'LESOTO',
    'LIBÉRIA',
    'LÍBIA',
    'LUXEMBURGO',
    'MADAGÁSCAR',
    'MALÁSIA',
    'MALÁUI',
    'MALDIVAS',
    'MALI',
    'MALTA',
    'MAURITÂNIA',
    'MAURÍCIO',
    'MÉXICO',
    'MICRONÉSIA',
    'MÔNACO',
    'MONGÓLIA',
    'MONTENEGRO',
    'MARROCOS',
    'MOÇAMBIQUE',
    'MYANMAR (BIRMÂNIA)',
    'NAMÍBIA',
    'NAURU',
    'NEPAL',
    'NICARÁGUA',
    'NÍGER',
    'NIGÉRIA',
    'NORUEGA',
    'OMÃ',
    'PAÍS DE GALES',
    'PAÍSES BAIXOS (HOLANDA)',
    'PAQUISTÃO',
    'PANAMÁ',
    'PAPUA NOVA GUINÉ',
    'PARAGUAI',
    'PERU',
    'FILIPINAS',
    'POLÔNIA',
    'PORTUGAL',
    'QATAR',
    'QUÊNIA',
    'QUIRGUISTÃO',
    'REINO UNIDO',
    'REPÚBLICA CENTRO-AFRICANA',
    'REPÚBLICA DEMOCRÁTICA DO CONGO',
    'REPÚBLICA DOMINICANA',
    'REPÚBLICA TCHECA',
    'ROMÊNIA',
    'RUANDA',
    'RÚSSIA',
    'SAMOA',
    'SAN MARINO',
    'SANTA LÚCIA',
    'SÃO CRISTÓVÃO E NEVES',
    'SÃO TOMÉ E PRÍNCIPE',
    'SENEGAL',
    'SÉRVIA',
    'SINGAPURA',
    'SÍRIA',
    'SOMÁLIA',
    'SRI LANKA',
    'SUDÃO',
    'SUDÃO DO SUL',
    'SUÉCIA',
    'SUÍÇA',
    'SURINAME',
    'TAILÂNDIA',
    'TAJIQUISTÃO',
    'TANZÂNIA',
    'TIMOR LESTE',
    'TOGO',
    'TONGA',
    'TRINIDAD E TOBAGO',
    'TUNÍSIA',
    'TURCOMENISTÃO',
    'TURQUEMENISTÃO',
    'TUVALU',
    'UCRÂNIA',
    'UGANDA',
    'URUGUAI',
    'UZBEQUISTÃO',
    'VANUATU',
    'VATICANO (SANTA SÉ)',
    'VENEZUELA',
    'VIETNÃ',
    'ZÂMBIA',
    'ZIMBÁBUE'
];

export const countriesWithFemaleNames = [
    'ÁFRICA DO SUL',
    'AMÉRICA DO SUL',
    'ALEMANHA',
    'ANDORRA',
    'ANGOLA',
    'ARÁBIA SAUDITA',
    'ARGÉLIA',
    'ARGENTINA',
    'ARMÊNIA',
    'AUSTRÁLIA',
    'ÁUSTRIA',
    'BÉLGICA',
    'BIELORRÚSSIA',
    'BIRMÂNIA (MYANMAR)',
    'BOLÍVIA',
    'BÓSNIA E HERZEGOVINA',
    'BOTSUANA',
    'BULGÁRIA',
    'BULGÁRIA',
    'BURUNDI',
    'CHINA',
    'COLÔMBIA',
    'COREIA DO NORTE',
    'COREIA DO SUL',
    'COSTA RICA',
    'CROÁCIA',
    'DINAMARCA',
    'DOMINICA',
    'ESLOVÁQUIA',
    'ESLOVÊNIA',
    'ESPANHA',
    'ESTÔNIA',
    'ETIÓPIA',
    'FINLÂNDIA',
    'FRANÇA',
    'GEÓRGIA',
    'GRÉCIA',
    'GUATEMALA',
    'GUIANA',
    'GUINÉ',
    'GUINÉ-BISSAU',
    'GUINÉ EQUATORIAL',
    'HOLANDA (PAÍSES BAIXOS)',
    'HONDURAS',
    'HUNGRIA',
    'ÍNDIA',
    'INDONÉSIA',
    'INGLATERRA',
    'IRLANDA',
    'ISLÂNDIA',
    'ITÁLIA',
    'JAMAICA',
    'JORDÂNIA',
    'LETÔNIA',
    'LÍBIA',
    'LITUÂNIA',
    'MACEDÔNIA DO NORTE',
    'MALÁSIA',
    'MAURITÂNIA',
    'MICRONÉSIA',
    'MOLDÁVIA',
    'NAMÍBIA',
    'NICARÁGUA',
    'NIGÉRIA',
    'NORUEGA',
    'NOVA ZELÂNDIA',
    'PALESTINA',
    'PANAMÁ',
    'PAPUA-NOVA GUINÉ',
    'POLÔNIA',
    'REPÚBLICA CENTRO-AFRICANA',
    'REPÚBLICA DOMINICANA',
    'REPÚBLICA TCHECA',
    'ROMÊNIA',
    'RÚSSIA',
    'SÉRVIA',
    'SÍRIA',
    'SOMÁLIA',
    'SUÉCIA',
    'SUÍÇA',
    'TAILÂNDIA',
    'TANZÂNIA',
    'TUNÍSIA',
    'TURQUIA',
    'UCRÂNIA',
    'UGANDA',
    'VENEZUELA',
    'ZÂMBIA',
    'ZIMBÁBUE'
];