import {Injectable} from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class CountriesService {

    getCountries() {
        return [
            { value: 1, name: 'Afeganistão' },
            { value: 2, name: 'África do Sul' },
            { value: 3, name: 'Albânia' },
            { value: 4, name: 'Alemanha' },
            { value: 5, name: 'Andorra' },
            { value: 6, name: 'Angola' },
            { value: 7, name: 'Antígua e Barbuda' },
            { value: 8, name: 'Arábia Saudita' },
            { value: 9, name: 'Argélia' },
            { value: 10, name: 'Argentina' },
            { value: 11, name: 'Armênia' },
            { value: 12, name: 'Austrália' },
            { value: 13, name: 'Áustria' },
            { value: 14, name: 'Azerbaijão' },
            { value: 15, name: 'Bahamas' },
            { value: 16, name: 'Bangladesh' },
            { value: 17, name: 'Barbados' },
            { value: 18, name: 'Barein' },
            { value: 19, name: 'Bélgica' },
            { value: 20, name: 'Belize' },
            { value: 21, name: 'Benim' },
            { value: 22, name: 'Bielorrússia' },
            { value: 23, name: 'Bolívia' },
            { value: 24, name: 'Bósnia e Herzegovina' },
            { value: 25, name: 'Botsuana' },
            { value: 26, name: 'Brasil' },
            { value: 27, name: 'Brunei' },
            { value: 28, name: 'Bulgária' },
            { value: 29, name: 'Burkina Faso' },
            { value: 30, name: 'Burundi' },
            { value: 31, name: 'Butão' },
            { value: 32, name: 'Cabo Verde' },
            { value: 33, name: 'Camarões' },
            { value: 34, name: 'Camboja' },
            { value: 35, name: 'Canadá' },
            { value: 36, name: 'Catar' },
            { value: 37, name: 'Cazaquistão' },
            { value: 38, name: 'Chade' },
            { value: 39, name: 'Chile' },
            { value: 40, name: 'China' },
            { value: 41, name: 'Chipre' },
            { value: 42, name: 'Colômbia' },
            { value: 43, name: 'Comores' },
            { value: 44, name: 'Coreia do Norte' },
            { value: 45, name: 'Coreia do Sul' },
            { value: 46, name: 'Costa do Marfim' },
            { value: 47, name: 'Costa Rica' },
            { value: 48, name: 'Croácia' },
            { value: 49, name: 'Cuba' },
            { value: 50, name: 'Dinamarca' },
            { value: 51, name: 'Djibuti' },
            { value: 52, name: 'Dominica' },
            { value: 53, name: 'Egito' },
            { value: 54, name: 'El Salvador' },
            { value: 55, name: 'Emirados Árabes Unidos' },
            { value: 56, name: 'Equador' },
            { value: 57, name: 'Eritreia' },
            { value: 58, name: 'Eslováquia' },
            { value: 59, name: 'Eslovênia' },
            { value: 60, name: 'Espanha' },
            { value: 61, name: 'Estados Unidos' },
            { value: 62, name: 'Estônia' },
            { value: 63, name: 'Eswatini' },
            { value: 64, name: 'Etiópia' },
            { value: 65, name: 'Fiji' },
            { value: 66, name: 'Filipinas' },
            { value: 67, name: 'Finlândia' },
            { value: 68, name: 'França' },
            { value: 69, name: 'Gabão' },
            { value: 70, name: 'Gâmbia' },
            { value: 71, name: 'Gana' },
            { value: 72, name: 'Geórgia' },
            { value: 73, name: 'Granada' },
            { value: 74, name: 'Grécia' },
            { value: 75, name: 'Guatemala' },
            { value: 76, name: 'Guiana' },
            { value: 77, name: 'Guiné' },
            { value: 78, name: 'Guiné-Bissau' },
            { value: 79, name: 'Haiti' },
            { value: 80, name: 'Honduras' },
            { value: 81, name: 'Hungria' },
            { value: 82, name: 'Iêmen' },
            { value: 83, name: 'Ilhas Maldivas' },
            { value: 84, name: 'Índia' },
            { value: 85, name: 'Indonésia' },
            { value: 86, name: 'Irã' },
            { value: 87, name: 'Iraque' },
            { value: 88, name: 'Irlanda' },
            { value: 89, name: 'Islândia' },
            { value: 90, name: 'Israel' },
            { value: 91, name: 'Itália' },
            { value: 92, name: 'Jamaica' },
            { value: 93, name: 'Japão' },
            { value: 94, name: 'Jordânia' },
            { value: 95, name: 'Letônia' },
            { value: 96, name: 'Líbano' },
            { value: 97, name: 'Líbia' },
            { value: 98, name: 'Malásia' },
            { value: 99, name: 'Moçambique' },
            { value: 100, name: 'Zimbábue' },
        ];
    }
}
